# ~/.zshrc - Interactive shell configuration

# Path to Oh-My-Zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Oh-My-Zsh theme (not used since we use Starship)
ZSH_THEME=""

# Oh-My-Zsh plugins
plugins=(
    git
    docker
    npm
    node
    python
    golang
    kubectl
    terraform
    aws
    brew
    macos
)

# Load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# Load zsh-autosuggestions (installed via Homebrew)
if [ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
elif [ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# NVM (Node Version Manager) setup
export NVM_DIR="$HOME/.nvm"
if [ -s "/opt/homebrew/opt/nvm/nvm.sh" ]; then
    source "/opt/homebrew/opt/nvm/nvm.sh"  # M1/M2/M3 Macs
elif [ -s "/usr/local/opt/nvm/nvm.sh" ]; then
    source "/usr/local/opt/nvm/nvm.sh"     # Intel Macs
fi

# NVM bash completion
if [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ]; then
    source "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
elif [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ]; then
    source "/usr/local/opt/nvm/etc/bash_completion.d/nvm"
fi

# Starship prompt (must be at the end)
if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi

# Node version management function
if [ -f "$HOME/.config/shell-functions/nvm-auto-switch.zsh" ]; then
    source "$HOME/.config/shell-functions/nvm-auto-switch.zsh"
fi

# GCloud CLI autocompletion
if [ -f "/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc" ]; then
    source "/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc"
fi

# GCloud CLI tools PATH export
if [ -f "/opt/homebrew/share/google-cloud-sdk/path.zsh.inc" ]; then
    source "/opt/homebrew/share/google-cloud-sdk/path.zsh.inc"
fi

# Custom aliases
if [ -f "$HOME/.config/aliases/custom-aliases.zsh" ]; then
    source "$HOME/.config/aliases/custom-aliases.zsh"
fi
